language: php

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
 - sudo apt-get install -qq python-numpy python-scipy
 - pip install numpy

install:
  - composer install --prefer-source --no-interaction
  # PHPUnit
  - ./vendor/bin/phpunit --version

before_script:
    # Install Code climate reporter
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
  # Run PHP unit tests
  - ./vendor/bin/phpunit -c test/Unit/phpunit.xml.dist
  # Run benchmark tests
  - ./test/Benchmark/bench.sh

after_script:
  # Code climate
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
